"""add ai context to business

Revision ID: 27b4e1c499f0
Revises: 9c245ff738db
Create Date: 2026-07-24 13:13:06.397676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b4e1c499f0'
down_revision: Union[str, None] = '9c245ff738db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('ai_context', sa.Text(), nullable=True))
    op.add_column('businesses', sa.Column('ai_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'ai_enabled')
    op.drop_column('businesses', 'ai_context')
    # ### end Alembic commands ###
